org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.WindowsSelectorProvider
android.useAndroidX=true
org.gradle.daemon=false
org.gradle.vfs.watch=false
systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv6Addresses=false
systemProp.java.nio.channels.spi.SelectorProvider=sun.nio.ch.WindowsSelectorProvider
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
